---
name : Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name : start
        run : docker-compose up -d
      - name : start2
        run : docker-compose up 
      - name: Test
        run: docker-compose run --rm sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm sh -c "flake8"

